version: '3.4'

services:
  cozastore.server.users.consumers.sendconfirmationemailmessage:
    image: ${DOCKER_REGISTRY-}cozastoreserverusersconsumerssendconfirmationemailmessage
    build:
      context: .
      dockerfile: Services/Users/CozaStore.Server.Users.Consumers.SendConfirmEmailMessage/Dockerfile
    depends_on:
        - rabbitmq
    networks:
        - rabbitmq_go_net
  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./docker-volumes/rabbitmq/data/:/var/lib/rabbitmq/
        - ./docker-volumes/rabbitmq/log/:/var/log/rabbitmq/
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge